# Generated by Django 3.2.4 on 2021-07-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(default='Hi', max_length=255),
        ),
    ]
